# Generated by Django 2.2.4 on 2019-11-06 17:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neonato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato', models.CharField(help_text='Apellido Paterno - Apellido Materno - RN', max_length=100, verbose_name='Datos del R.N.')),
                ('fecha', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Fecha y Hora Nacimiento')),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=20)),
                ('tipo', models.CharField(choices=[('Natural', 'Natural'), ('Cesarea', 'Cesarea')], max_length=20, verbose_name='Tipo de Parto')),
                ('dni', models.CharField(max_length=8, verbose_name='DNI - Madre o Titular')),
                ('reg', models.BooleanField(default=False, verbose_name='Registrado')),
                ('user', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
