# Generated by Django 2.2.4 on 2019-12-11 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_auto_20191121_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaObservacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingreso', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Fecha y Hora Ingreso')),
                ('dni', models.CharField(max_length=8, verbose_name='D.N.I.')),
                ('apellido1', models.CharField(blank=True, max_length=35, verbose_name='Apellido Paterno')),
                ('apellido2', models.CharField(blank=True, max_length=35, verbose_name='Apellido Materno')),
                ('nombre1', models.CharField(blank=True, max_length=35, verbose_name='Primer Nombre')),
                ('nombre2', models.CharField(blank=True, max_length=35, verbose_name='Segundo Nombre')),
                ('edad', models.CharField(blank=True, max_length=3, verbose_name='Edad')),
                ('historia', models.CharField(blank=True, max_length=8, verbose_name='Hist. Clinica')),
                ('ambiente', models.CharField(choices=[('Observacion Adultos', 'Observacion Adultos'), ('Observacion Pediatricos', 'Observacion Pediatricos')], max_length=30)),
                ('cama', models.CharField(choices=[('CAMA-01', 'CAMA-01'), ('CAMA-02', 'CAMA-02'), ('CAMA-03', 'CAMA-03'), ('CAMA-04', 'CAMA-04'), ('CAMA-05', 'CAMA-05'), ('CAMA-06', 'CAMA-06'), ('CAMA-07', 'CAMA-07'), ('CAMA-08', 'CAMA-08'), ('CAMA-09', 'CAMA-09'), ('CAMA-10', 'CAMA-10'), ('CAMA-11', 'CAMA-11'), ('CAMA-12', 'CAMA-12'), ('CAMA-13', 'CAMA-13'), ('CAMA-14', 'CAMA-14'), ('CAMA-15', 'CAMA-15'), ('CAMA-16', 'CAMA-16'), ('CAMA-17', 'CAMA-17'), ('CAMA-18', 'CAMA-18'), ('CAMA-19', 'CAMA-19'), ('CAMA-20', 'CAMA-20'), ('CAMA-21', 'CAMA-21'), ('CAMA-22', 'CAMA-22'), ('CAMA-23', 'CAMA-23'), ('CAMA-24', 'CAMA-24'), ('CAMA-25', 'CAMA-25'), ('CAMA-26', 'CAMA-26')], max_length=30, verbose_name='Cama')),
                ('salida', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Fecha y Hora Alta')),
                ('estado', models.CharField(choices=[('Hospitalizado', 'Hospitalizado'), ('Transferecia Interna', 'Transferencia Interna'), ('Transferecia Externa', 'Transferencia Externa'), ('Alta', 'Alta'), ('Morge', 'Morge')], max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='neonato',
            name='dni',
            field=models.CharField(max_length=8, verbose_name='DNI - Madre o Tit.'),
        ),
        migrations.AlterField(
            model_name='neonato',
            name='tipo',
            field=models.CharField(choices=[('Natural', 'Natural'), ('Cesarea', 'Cesarea')], max_length=20, verbose_name='Tipo - Parto'),
        ),
        migrations.AlterField(
            model_name='neonato',
            name='transf',
            field=models.CharField(blank=True, choices=[('Ucin', 'Ucin'), ('InterMedio - 1', 'InterMedio - 1'), ('InterMedio - 2', 'InterMedio - 2')], max_length=20, verbose_name='Transferir.'),
        ),
    ]
