# Generated by Django 2.2.4 on 2019-12-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_auto_20191211_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaobservacion',
            name='ambiente',
            field=models.CharField(choices=[('Observacion Adulto', 'Observacion Adulto'), ('Observacion Pediatrico', 'Observacion Pediatrico')], max_length=30),
        ),
    ]
