# Generated by Django 2.2.4 on 2019-12-12 06:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_auto_20191212_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoMedico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='FECHA')),
                ('topico', models.CharField(choices=[('JEFE DE GUARDIA', 'JEFE DE GUARDIA'), ('MEDICINA 1', 'MEDICINA 1'), ('MEDICINA 2', 'MEDICINA 2'), ('PEDIATRIA', 'PEDIATRIA'), ('CIRUGIA', 'CIRUGIA'), ('GINEGOLOGIA', 'GINECOLOGIA'), ('TRIAJE', 'TRIAJE')], max_length=40)),
                ('medico', models.CharField(max_length=40)),
                ('turno', models.CharField(blank=True, choices=[('GUARDIA DIURNA', 'GUARDIA DIURNA'), ('GUARDIA NOCTURNA', 'GUARDIA NOCTURNA')], max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='salaobservacion',
            name='ambiente',
            field=models.CharField(choices=[('OBS. ADULTO', 'OBS. ADULTO'), ('OBS. PEDIATRICO', 'OBS. PEDIATRICO')], max_length=30),
        ),
        migrations.AlterField(
            model_name='salaobservacion',
            name='estado',
            field=models.CharField(choices=[('HOSPITALIZADO', 'HOSPITALIZADO'), ('TRANSF. INTERNA', 'TRANSF. INTERNA'), ('TRANSF. EXTERNA', 'TRANSF. EXTERNA'), ('ALTA', 'ALTA'), ('MORGE', 'MORGE')], max_length=30),
        ),
    ]
