# Generated by Django 2.2.4 on 2019-12-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_auto_20191212_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnomedico',
            name='topico',
            field=models.CharField(choices=[('JEFE DE GUARDIA', 'JEFE DE GUARDIA'), ('MEDICINA 1', 'MEDICINA 1'), ('MEDICINA 2', 'MEDICINA 2'), ('PEDIATRIA', 'PEDIATRIA'), ('CIRUGIA', 'CIRUGIA'), ('GINEGOLOGIA', 'GINECOLOGIA'), ('TRAUMATOLOGIA', 'TRAUMATOLOGIA'), ('TRIAJE', 'TRIAJE')], max_length=40),
        ),
    ]
