# Generated by Django 2.2.4 on 2020-05-05 08:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0007_auto_20191212_0143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='turnomedico',
            name='topico',
            field=models.CharField(choices=[('JEFE DE GUARDIA', 'JEFE DE GUARDIA'), ('SALA OBSERVACION', 'SALA OBSERVACION'), ('MEDICINA 1', 'MEDICINA 1'), ('MEDICINA 2', 'MEDICINA 2'), ('PEDIATRIA', 'PEDIATRIA'), ('CIRUGIA', 'CIRUGIA'), ('GINEGOLOGIA', 'GINECOLOGIA'), ('TRAUMATOLOGIA', 'TRAUMATOLOGIA'), ('TRIAJE', 'TRIAJE')], max_length=40),
        ),
        migrations.CreateModel(
            name='Tercero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, verbose_name='D.N.I.')),
                ('fecha', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Registro')),
                ('paciente', models.CharField(blank=True, max_length=70, verbose_name='Apellidos y Nombres')),
                ('domicilio', models.CharField(blank=True, max_length=60, verbose_name='Direccion')),
                ('edad', models.PositiveSmallIntegerField(null=True)),
                ('sexo', models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMENINO', 'FEMENINO')], max_length=20)),
                ('celular', models.CharField(help_text='Numero de Contacto', max_length=9, verbose_name='Telefono Movil')),
                ('condicion', models.CharField(choices=[('TERCERO', 'TERCERO'), ('SEGURO NO VIGENTE', 'SEGURO NO VIGENTE')], max_length=30)),
                ('observacion', models.TextField(help_text='observaciones adicionales', max_length=100)),
                ('profesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Profesione', verbose_name='Profesion / Ocupacion')),
            ],
        ),
    ]
