# Generated by Django 2.2.4 on 2020-05-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0008_auto_20200505_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tercero',
            name='profesion',
            field=models.CharField(choices=[('BOMBERO', 'BOMBERO'), ('POLICIA', 'POLICIA'), ('PERSONAL DE SALUD', 'PERSONAL DE SALUD'), ('OTRAS PROFESIONES', 'OTRAS PROFESIONES')], max_length=30),
        ),
        migrations.DeleteModel(
            name='Profesione',
        ),
    ]
