# Generated by Django 2.2.4 on 2021-01-12 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0009_auto_20200505_0611'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDataReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=250, verbose_name='Filename')),
                ('fecha', models.DateTimeField(default=datetime.datetime.now, verbose_name='Registro')),
            ],
        ),
        migrations.AlterField(
            model_name='tercero',
            name='domicilio',
            field=models.CharField(max_length=60, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='edad',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Registro'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='paciente',
            field=models.CharField(max_length=70, verbose_name='Apellidos y Nombres'),
        ),
    ]
