# Generated by Django 2.2.4 on 2021-01-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0010_auto_20210112_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedatareport',
            name='fecha',
            field=models.DateTimeField(verbose_name='Registro'),
        ),
    ]
