# Generated by Django 2.2.4 on 2021-02-04 02:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registro', '0011_auto_20210112_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Censo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=4)),
                ('ncama', models.IntegerField()),
                ('adm', models.BooleanField(default=False)),
                ('transferencia', models.CharField(max_length=250)),
                ('alta', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingreso', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Fecha y Hora Ingreso')),
                ('dni', models.CharField(max_length=8, verbose_name='D.N.I.')),
                ('nombre', models.CharField(blank=True, max_length=35, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, max_length=35, verbose_name='Apellidos')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('estacion', models.CharField(max_length=250)),
                ('ncamas', models.IntegerField()),
                ('fecha', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Fecha de Registro')),
            ],
        ),
        migrations.DeleteModel(
            name='SalaObservacion',
        ),
        migrations.AddField(
            model_name='censo',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Paciente'),
        ),
        migrations.AddField(
            model_name='censo',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Servicio'),
        ),
        migrations.AddField(
            model_name='censo',
            name='usuario',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
