# Generated by Django 2.2.4 on 2021-02-04 05:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registro', '0012_auto_20210203_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Fecha')),
                ('pagare', models.CharField(max_length=7, verbose_name='N° de Pagare')),
                ('contingencia', models.CharField(choices=[('NO ACREDITADO', 'NO ACREDITADO'), ('AGRESION POR TERCEROS', 'AGRESION POR TERCEROS'), ('ACCIDENTE DE TRANSITO', 'ACCIDENTE DE TRANSITO'), ('ACCIDENTE DE MOTO', 'ACCIDENTE DE MOTO'), ('PARTICULAR', 'PARTICULAR'), ('INTENTO DE SUICIDIO', 'INTENTO DE SUICIDIO')], max_length=30, verbose_name='Contingencia')),
                ('dni1', models.CharField(max_length=8, verbose_name='D.N.I.')),
                ('paciente', models.CharField(max_length=35, verbose_name='Datos del Paciente')),
                ('dni2', models.CharField(max_length=8, verbose_name='D.N.I')),
                ('aval', models.CharField(max_length=40, verbose_name='Datos del Aval')),
                ('domicilio', models.CharField(max_length=35, verbose_name='Domicilio')),
                ('movil', models.CharField(max_length=9, verbose_name='Telefono / Movil')),
                ('obs', models.CharField(max_length=200, verbose_name='Deposito/Garantia')),
                ('user', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
        ),
    ]
