# Generated by Django 2.2.4 on 2021-02-04 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0013_pagare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagare',
            name='user',
        ),
    ]
