# Generated by Django 3.1.6 on 2021-02-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0014_remove_pagare_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='censo',
            name='tipo',
        ),
        migrations.AddField(
            model_name='censo',
            name='gone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='censo',
            name='salida',
            field=models.CharField(default='-', max_length=250),
        ),
    ]
