# Generated by Django 2.2.4 on 2021-02-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0015_auto_20210206_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='habitacion',
            field=models.CharField(default='-', max_length=250),
            preserve_default=False,
        ),
    ]
