# Generated by Django 2.2.4 on 2021-02-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0016_servicio_habitacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='censo',
            name='alta',
        ),
        migrations.RemoveField(
            model_name='censo',
            name='gone',
        ),
        migrations.AddField(
            model_name='censo',
            name='salida_servicio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='censo',
            name='salida_tipo',
            field=models.CharField(default='ALTA', max_length=250),
        ),
    ]
