# Generated by Django 2.2.4 on 2021-02-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0017_auto_20210210_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='censo',
            name='salida_servicio',
            field=models.CharField(default='---', max_length=250),
        ),
    ]
