# Generated by Django 2.2.4 on 2021-02-11 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0018_auto_20210210_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='synced',
            field=models.BooleanField(default=False),
        ),
    ]
