# Generated by Django 2.2.4 on 2021-02-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0019_servicio_synced'),
    ]

    operations = [
        migrations.AddField(
            model_name='censo',
            name='input_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='censo',
            name='output_synced',
            field=models.BooleanField(default=False),
        ),
    ]
