# Generated by Django 2.2.4 on 2021-03-25 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registro', '0021_auto_20210214_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagare',
            name='ref',
            field=models.TextField(default=1, help_text='observaciones de Acreditacion', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagare',
            name='user',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
    ]
