# Generated by Django 2.2.4 on 2021-03-29 21:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0023_auto_20210325_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagare',
            name='aval',
            field=models.CharField(blank=True, max_length=40, verbose_name='Datos del Aval'),
        ),
        migrations.AlterField(
            model_name='pagare',
            name='check',
            field=models.BooleanField(default=False, help_text='Completa Informacion', verbose_name='Rev.'),
        ),
        migrations.AlterField(
            model_name='pagare',
            name='contingencia',
            field=models.CharField(choices=[('ANULADO', 'ANULADO'), ('NO ACREDITADO', 'NO ACREDITADO'), ('AGRESION POR TERCEROS', 'AGRESION POR TERCEROS'), ('ACCIDENTE DE TRANSITO', 'ACCIDENTE DE TRANSITO'), ('ACCIDENTE DE MOTO', 'ACCIDENTE DE MOTO'), ('PARTICULAR', 'PARTICULAR'), ('INTENTO DE SUICIDIO', 'INTENTO DE SUICIDIO')], max_length=30, verbose_name='Contingencia'),
        ),
        migrations.AlterField(
            model_name='pagare',
            name='dni1',
            field=models.CharField(blank=True, max_length=8, verbose_name='D.N.I.'),
        ),
        migrations.AlterField(
            model_name='pagare',
            name='dni2',
            field=models.CharField(blank=True, max_length=8, verbose_name='D.N.I'),
        ),
        migrations.AlterField(
            model_name='pagare',
            name='domicilio',
            field=models.CharField(blank=True, max_length=40, verbose_name='Domicilio'),
        ),
        migrations.AlterField(
            model_name='pagare',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='pagare',
            name='movil',
            field=models.CharField(blank=True, max_length=9, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='pagare',
            name='obs',
            field=models.CharField(blank=True, help_text='Deposito/Garantia', max_length=200, verbose_name='DEP.'),
        ),
        migrations.AlterField(
            model_name='pagare',
            name='paciente',
            field=models.CharField(blank=True, max_length=35, verbose_name='Datos del Paciente'),
        ),
        migrations.AlterField(
            model_name='pagare',
            name='pagare',
            field=models.CharField(max_length=7, verbose_name='N° Pagare'),
        ),
        migrations.AlterField(
            model_name='pagare',
            name='ref',
            field=models.TextField(blank=True, help_text='Observaciones de Acreditacion', max_length=100, verbose_name='Acredita-Obs'),
        ),
        migrations.AlterField(
            model_name='pagare',
            name='user',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
